/* Two pulse voices, triangle bass, noise and one DPCM-style sample voice. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ContraAudio=api;})(typeof window!=='undefined'?window:this,function(){
'use strict';
const SCORES={city:[40,47,52,55,54,52,47,43,40,47,52,59,55,54,50,47],factory:[38,45,50,53,50,45,41,45,38,46,50,55,53,50,46,41],hive:[36,43,48,49,55,49,48,43,36,42,48,51,54,51,48,42],nes:[40,47,52,55,54,52,47,43]};
class Sound{
 constructor(samples={},host=typeof window!=='undefined'?window:{}){this.enabled=false;this.context=null;this.host=host;this.samples=samples;this.voices=new Map();this.buffers=new Map();this.stage='';this.nextBeat=0;this.beat=0;this.running=false;}
 unlock(){if(!this.enabled)return;try{const Audio=this.host.AudioContext||this.host.webkitAudioContext;if(!Audio)return;if(!this.context)this.context=new Audio();if(this.context.state==='suspended')this.context.resume().catch(()=>{});}catch(_){this.enabled=false;}}
 stopVoice(key){const v=this.voices.get(key);if(!v)return;try{v.node.stop();}catch(_){}v.node.disconnect();v.gain.disconnect();this.voices.delete(key);}
 stop(){for(const key of [...this.voices.keys()])this.stopVoice(key);this.running=false;}
 play(node,key,duration,volume){const c=this.context;if(!c||!this.enabled||c.state!=='running')return;this.stopVoice(key);const gain=c.createGain(),now=c.currentTime;gain.gain.setValueAtTime(volume,now);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);node.connect(gain);gain.connect(c.destination);const voice={node,gain};this.voices.set(key,voice);node.onended=()=>{node.disconnect();gain.disconnect();if(this.voices.get(key)===voice)this.voices.delete(key);};node.start(now);node.stop(now+duration);}
 tone(freq,end,duration,type='square',volume=.025,key='pulse1'){if(!this.enabled||!this.context||this.context.state!=='running')return;const node=this.context.createOscillator();node.type=type;node.frequency.setValueAtTime(freq,this.context.currentTime);node.frequency.exponentialRampToValueAtTime(Math.max(20,end),this.context.currentTime+duration);this.play(node,key,duration,volume);}
 sample(id,volume=.09){if(!this.enabled||!this.context||this.context.state!=='running')return;const s=this.samples[id];if(!s?.data.length)return;if(!this.buffers.has(id)){const b=this.context.createBuffer(1,s.data.length,s.rate),channel=b.getChannelData(0);for(let i=0;i<s.data.length;i++)channel[i]=(s.data[i]-64)/64;this.buffers.set(id,b);}const node=this.context.createBufferSource();node.buffer=this.buffers.get(id);this.play(node,'sample',node.buffer.duration,volume);}
 noise(duration=.12,volume=.025){if(!this.enabled||!this.context||this.context.state!=='running')return;const c=this.context,b=c.createBuffer(1,Math.ceil(c.sampleRate*duration),c.sampleRate),out=b.getChannelData(0);let lfsr=1;for(let i=0;i<out.length;i++){if(i%8===0)lfsr=(lfsr>>1)|(((lfsr^(lfsr>>1))&1)<<14);out[i]=(lfsr&1)?.4:-.4;}const node=c.createBufferSource();node.buffer=b;this.play(node,'noise',duration,volume);}
 update(world){if(!this.enabled||world.state!=='playing'||!this.context||this.context.state!=='running'){if(this.running||this.voices.size)this.stop();return;}const stage=world.level.id||'nes';if(!this.running||this.stage!==stage){this.stop();this.running=true;this.stage=stage;this.nextBeat=this.context.currentTime;this.beat=0;}const now=this.context.currentTime;if(now<this.nextBeat)return;this.nextBeat=now+(world.boss.activated?.11:.14);const score=SCORES[stage]||SCORES.city,n=score[this.beat%score.length],freq=440*2**((n+24-69)/12);this.tone(freq,freq,.1,'square',.012,'pulse2');if(this.beat%2===0)this.tone(freq/4,freq/4,.2,'triangle',.035,'triangle');if(this.beat%4===0)this.sample('kick',.055);else if(this.beat%4===2)this.sample('snare',.045);else if(this.beat%8===7)this.sample('noise',.025);else this.noise(.04,.01);this.beat++;}
 event(e){if(e.type==='shot')this.tone(e.code==='L'?900:210,e.code==='H'?320:60,.06,'square',.016);if(e.type==='jump')this.tone(260,540,.09,'square',.012);if(['explosion','bomb','bossDead'].includes(e.type)){this.noise(e.big?.3:.14,.055);this.sample('kick');}if(e.type==='death'){this.sample('death',.09);this.noise(.2,.035);}if(e.type==='pickup'||e.type==='swap')this.tone(520,1300,.16,'triangle',.04);if(e.type==='win')this.tone(392,1568,.7,'triangle',.045);}
}
return{Sound,SCORES};});
