(function(){'use strict';const $=id=>document.getElementById(id),S=window.ContraSpirits,P=window.SpiritsPilot,renderer=new window.ContraRenderer($('game')),STEP=1/60,sound=new window.ContraAudio.Sound(window.SpiritsSamples.samples);let token=0,audioWorld;
 function run(stage,seed,until='won'){const w=new S.SpiritsWorld(stage,seed),pilot=new P();w.reset();let frames=0;while(w.state==='playing'&&frames<18000){w.update(STEP,pilot.next(w));w.drainEvents();frames++;if(until==='scene'&&w.player.x>130||until==='boss'&&w.boss.activated)break;}return{w,frames};}
 function audit(){return{canvas:document.querySelectorAll('canvas').length,images:document.querySelectorAll('img,svg').length,rasterRequests:performance.getEntriesByType('resource').filter(e=>/\.(png|gif|jpe?g|webp|svg)(\?|$)/i.test(e.name)).length};}
 function show(stage,until){token++;const {w,frames}=run(stage,1337,until);renderer.clear();renderer.draw(w,0);$('status').textContent=stage+' / '+until;$('results').textContent=JSON.stringify({stage,state:w.state,frames,lives:w.lives,weapon:w.player.weapon.code,...audit()},null,2);}
 document.querySelectorAll('[data-scene]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.scene,'scene')));document.querySelectorAll('[data-boss]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.boss,'boss')));
 $('run-all').addEventListener('click',()=>{token++;const results=[];for(const stage of S.STAGES)for(const seed of [1,7,27,42,123,256,512,1024,1337,9001]){const {w,frames}=run(stage.id,seed);results.push({stage:stage.id,seed,state:w.state,frames,lives:w.lives,deaths:w.deaths,score:w.score});renderer.draw(w,0);}$('status').textContent=results.filter(r=>r.state==='won').length+'/30 通关通过';$('results').textContent=JSON.stringify({results,...audit()},null,2);});
 $('run-render').addEventListener('click',()=>{const mine=++token,results=[],costs=[],intervals=[];let count=0,start,last,w,pilot,maxNodes=0;function frame(now){if(mine!==token)return;if(start===undefined)start=now;if(last!==undefined)intervals.push(now-last);last=now;if(count%200===0){w=new S.SpiritsWorld(S.STAGES[Math.floor(count/200)].id);w.reset();pilot=new P();renderer.clear();}for(let i=0;i<16;i++){w.update(STEP,pilot.next(w));for(const e of w.drainEvents())renderer.event(e);}const before=performance.now();renderer.draw(w,16*STEP);costs.push(performance.now()-before);maxNodes=Math.max(maxNodes,$('game').querySelectorAll('*').length);count++;$('status').textContent='性能测试 '+count+'/600';if(count%200===0)results.push({stage:w.level.id,state:w.state});if(count<600)return requestAnimationFrame(frame);costs.sort((a,b)=>a-b);intervals.sort((a,b)=>a-b);$('status').textContent='性能测试完成';$('results').textContent=JSON.stringify({frames:count,fps:Number((599000/(now-start)).toFixed(1)),renderP95Ms:costs[570],intervalP95Ms:intervals[569],maxNodes,results,...audit()},null,2);}requestAnimationFrame(frame);});
 $('audio-test').addEventListener('click',()=>{sound.enabled=true;sound.unlock();audioWorld=new S.SpiritsWorld('city');audioWorld.reset();$('status').textContent='试听中：四种 Contra III 短采样 + FC 原创编曲';let n=0;function tick(){if(!audioWorld)return;audioWorld.time+=STEP;sound.update(audioWorld);if(n%90===0)sound.event({type:n%180?'shot':'death'});n++;$('results').textContent=JSON.stringify({audioState:sound.context?.state,activeVoices:sound.voices.size,sampleBuffers:sound.buffers.size,stage:sound.stage},null,2);requestAnimationFrame(tick);}if(!sound.previewing){sound.previewing=true;requestAnimationFrame(tick);}});
 $('audio-stop').addEventListener('click',()=>{sound.enabled=false;sound.stop();audioWorld=null;sound.previewing=false;$('status').textContent='音频已停止';$('results').textContent=JSON.stringify({activeVoices:sound.voices.size});});
 window.addEventListener('blur',()=>{sound.enabled=false;sound.stop();audioWorld=null;sound.previewing=false;});show('city','scene');
})();
