'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.join(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const sprites=JSON.parse(read('assets/manifest.json')),bg=JSON.parse(read('assets/backgrounds.json'));
function rules(css){return new Map([...css.matchAll(/\.([\w-]+)::before\{background:(#[a-f0-9]{8});box-shadow:([^}]+)\}/g)].map(m=>[m[1],{background:m[2],shadows:m[3]}]));}
// Independently reconstruct visible RGBA from emitted CSS, including the origin pixel.
function raster(rule,w,h){assert.ok(rule);const b=Buffer.alloc(w*h*4),origin=Buffer.from(rule.background.slice(1),'hex');if(origin[3])origin.copy(b,0);for(const match of rule.shadows.matchAll(/(\d+)px (\d+)px #([a-f0-9]{8})/g)){const x=Number(match[1]),y=Number(match[2]);assert.ok(x<w&&y<h);assert.ok(x||y,'outer shadows cannot paint the origin pixel');Buffer.from(match[3],'hex').copy(b,(y*w+x)*4);}return b;}
function gradientRules(css){return new Map([...css.matchAll(/\.([\w-]+)\{width:(\d+)px;height:(\d+)px;background:([^}]+)\}/g)].map(m=>[m[1],{w:+m[2],h:+m[3],css:m[4]}]));}
function gradientRaster(rule){assert.ok(rule);const b=Buffer.alloc(rule.w*rule.h*4),rows=[...rule.css.matchAll(/linear-gradient\(90deg,([^)]*)\) 0px (\d+)px\/(\d+)px ([12])px no-repeat/g)];assert.equal(rows.length,rule.h);for(const row of rows.reverse()){const y=+row[2];assert.equal(+row[3],rule.w);for(const run of row[1].matchAll(/#([a-f0-9]{8}) (\d+)px (\d+)px/g)){const color=Buffer.from(run[1],'hex');if(!color[3])continue;for(let yy=y;yy<Math.min(rule.h,y+Number(row[4]));yy++)for(let x=+run[2];x<+run[3];x++)color.copy(b,(yy*rule.w+x)*4);}}return b;}
test('参考库全部233个文件和236帧均收录，原文件哈希一致',()=>{assert.equal(sprites.sourceFiles,233);assert.equal(Object.keys(sprites.assets).length,233);assert.equal(sprites.frameCount,236);assert.equal(fs.readdirSync(path.join(root,'assets/source')).length,233);for(const a of Object.values(sprites.assets))assert.equal(sha(fs.readFileSync(path.join(root,'assets/source',a.file))),a.sourceSha256,a.file);});
test('233个精灵的236帧 CSS 像素与源图可见RGBA逐像素一致',()=>{const all=rules(read('assets/nes-sprites.css'));for(const a of Object.values(sprites.assets))for(const f of a.frames)assert.equal(sha(raster(all.get('art-'+f.key),a.width,a.height)),f.visibleRgbaSha256,f.key);});
test('GIF保留四帧及原始帧时长，并用CSS离散动画切换',()=>{const a=sprites.assets.sprite_4e,css=read('assets/nes-sprites.css');assert.equal(a.frames.length,4);for(const f of a.frames)assert.ok(f.duration>0);assert.ok(css.includes(`art-sprite_4e ${a.frames.reduce((n,f)=>n+f.duration,0)}ms steps(1,end) infinite`));assert.ok(css.includes('@keyframes art-sprite_4e'));});
test('八关背景、八张缩略图、首关对象图原文件齐全',()=>{assert.equal(Object.keys(bg.maps).length,17);for(let i=1;i<=8;i++)assert.ok(bg.maps['stage-'+i]);for(const s of Object.values(bg.sources))assert.equal(sha(fs.readFileSync(path.join(root,'assets/background-source',s.file))),s.sha256,s.file);});
test('所有去重背景CSS图块可见RGBA一致，左上角没有透明孔',()=>{const all=rules(read('assets/nes-backgrounds.css'));assert.equal(all.size,bg.tileCount);for(let i=0;i<bg.tileCount;i++)assert.equal(sha(raster(all.get('bg-'+i),8,8)),bg.tiles[i].visibleRgbaSha256,'tile '+i);});
test('合并后的游戏场景块与对应原始地图像素完全一致',()=>{const patches=rules(read('assets/nes-patches.css')),tiles=rules(read('assets/nes-backgrounds.css'));for(const[name,p]of Object.entries(bg.patches)){const actual=raster(patches.get('patch-'+name),p.w,p.h),expected=Buffer.alloc(p.w*p.h*4),map=bg.maps[p.map];for(let y=0;y<p.h;y+=8)for(let x=0;x<p.w;x+=8){const id=map.tiles[(p.y+y)/8*map.cols+(p.x+x)/8],tile=raster(tiles.get('bg-'+id),8,8);for(let yy=0;yy<8;yy++)tile.copy(expected,((y+yy)*p.w+x)*4,yy*32,yy*32+32);}assert.equal(sha(actual),sha(expected),name);}});
test('游戏采用的CSS硬边渐变与全部精灵、场景源像素一致',()=>{const spritesCss=gradientRules(read('assets/nes-sprites-fast.css')),patchCss=gradientRules(read('assets/nes-patches-fast.css'));for(const a of Object.values(sprites.assets))for(const f of a.frames)assert.equal(sha(gradientRaster(spritesCss.get('art-'+f.key))),f.visibleRgbaSha256,f.key);for(const[name,p]of Object.entries(bg.patches))assert.equal(sha(gradientRaster(patchCss.get('patch-'+name))),p.visibleRgbaSha256,name);});
test('每张地图的索引、尺寸与游戏裁取范围均有效',()=>{for(const m of Object.values(bg.maps)){assert.equal(m.tiles.length,m.cols*m.rows);for(const t of m.tiles)assert.ok(Number.isInteger(t)&&t>=0&&t<bg.tileCount);}for(const p of Object.values(bg.patches)){const m=bg.maps[p.map];assert.ok(p.x>=0&&p.y>=0&&p.x+p.w<=m.width&&p.y+p.h<=m.height);assert.equal(p.x%8,0);assert.equal(p.y%8,0);}});
test('游戏与素材页不依赖Canvas、SVG或位图绘制',()=>{for(const f of ['index.html','qa.html','art.html']){const html=read(f);assert.doesNotMatch(html,/<(?:canvas|img|svg)\b/i);assert.ok(html.includes('css-renderer.js'));}assert.doesNotMatch(read('css-renderer.js'),/getContext\s*\(|drawImage\s*\(|new Image\s*\(/);for(const f of ['assets/nes-sprites.css','assets/nes-backgrounds.css','assets/stage1.css','css-renderer.css'])assert.doesNotMatch(read(f),/url\s*\(/i);});
