'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const R=require('../rom-city-core.js'),C=require('../core.js'),Pilot=require('../spirits-pilot.js'),ref=require('./fixtures/city-rom-reference.json'),actors=require('../assets/spirits-actors.json');
const fresh=()=>{const w=new R.RomCityWorld();w.reset();return w;};
test('首关坐标逐帧复核：130 帧自然输入，与 ROM 的 16.16 坐标完全一致',()=>{const w=fresh();for(const row of ref.movement){w.update(1/60,{right:row.right,jump:row.jump,fire:row.right});assert.equal(w.player.cx,row.x,'x frame '+row.frame);assert.equal(w.player.y+w.player.h,row.feet,'y frame '+row.frame);}});
test('原版图块分类与显存快照：5040 个碰撞记录，保留动态场景差异',()=>{let compared=0,dynamic=0;for(const[x,y,code,actual,base]of ref.terrainSamples){if(actual===base){assert.equal(R.DATA.collision[y*896+x],code);compared++;}else dynamic++;}assert.equal(compared,4968);assert.equal(dynamic,72);assert.ok(ref.checks.every(c=>c.total===c.collisionMatches));});
for(const code of ['M','S','C','H','L'])test(code+' 实际开火帧与独立 ROM 射击记录一致',()=>{
 const w=fresh();w.player.equip(new R.RomWeapon(code));const actual=[];for(let frame=0;frame<40;frame++){const n=w.player.weapon.serial;w.update(1/60,{fire:true});if(w.player.weapon.serial!==n)actual.push(frame);}
 const primaryFlag={M:1,S:2,C:3,H:4,L:11}[code],expected=[...new Set(ref.guns[code].births.filter(b=>b.flag===primaryFlag).map(b=>b.frame))];assert.deepEqual(actual,expected);
});
test('S 五个速度向量逐项匹配 ROM，残留两组子弹时不拼凑第三组',()=>{const gun=new R.RomWeapon('S'),ctx={time:0,x:60,y:80,angle:0,held:true},first=gun.tryFire(ctx);for(let i=0;i<5;i++){assert.equal(first[i].vx/60,ref.guns.S.first[i].vx);assert.equal(first[i].vy/60,ref.guns.S.first[i].vy);}const second=gun.tryFire({...ctx,time:4/60});first.slice(0,3).forEach(b=>b.alive=false);second.slice(0,2).forEach(b=>b.alive=false);assert.equal(gun.tryFire({...ctx,time:8/60}).length,0);first.forEach(b=>b.alive=false);assert.equal(gun.tryFire({...ctx,time:12/60}).length,5);});
test('30 命、双 M 初始槽，死亡只重置当前武器和炸弹，B 保护准确结束',()=>{const w=fresh();assert.equal(w.lives,30);assert.deepEqual(w.player.slots.map(g=>g.code),['M','M']);w.player.slots[1]=new R.RomWeapon('L');w.player.equip(new R.RomWeapon('C'));new R.RomPickup(0,0,'B').apply(w);for(let i=0;i<511;i++)w.update(1/60);assert.ok(w.player.barrier>0);assert.equal(w.hurtPlayer(),false);w.update(1/60);assert.equal(w.player.barrier,0);assert.equal(w.hurtPlayer(),true);assert.deepEqual(w.player.slots.map(g=>g.code),['M','L']);for(let i=0;i<61;i++)w.update(1/60);assert.equal(w.player.respawnTimer,0);assert.equal(w.player.y+w.player.h,200);});
test('补给来自原版触发表：开场 B 与炸弹是飞行胶囊，地面不预摆武器',()=>{const w=fresh();assert.equal(w.pickups.length,0);w.camera=16;w.spawnEvents();assert.equal(w.capsules.length,1);assert.equal(w.capsules[0].code,'B');assert.equal(w.capsules[0].facing,1);w.camera=128;w.spawnEvents();assert.equal(w.capsules[1].code,'bomb');assert.equal(w.capsules[1].facing,-1);w.capsules[0].takeDamage(2,w);assert.equal(w.pickups[0].code,'B');});
test('墙体锁镜头，击破后放开镜头并恢复地面通路',()=>{const w=fresh();w.camera=1968;w.spawnEvents();const g=w.gates[0];assert.ok(g);w.player.x=2170;w.update(1/60);assert.equal(w.camera,2048);g.takeDamage(999,w);assert.equal(g.alive,false);assert.deepEqual(w.level.removedWalls,[2208]);assert.ok(w.level.platforms.some(p=>p.x===2208&&p.w===96&&p.y===200));w.update(1/60,{right:true});assert.ok(w.camera>2048);});
test('士兵从左右边缘按移动方向行进，不追着玩家反复翻转',()=>{const w=fresh(),left=new R.RomEnemy(120,200,'runner',-1),right=new R.RomEnemy(40,200,'runner',1);left.update(1/60,w);right.update(1/60,w);assert.equal(left.cx,120-84.375/60);assert.equal(right.cx,40+99.375/60);w.player.x=220;left.update(1/60,w);assert.equal(left.facing,-1);});
test('碰撞检查包括补给，且镜头外未出现的对象不会挡弹',()=>{const w=fresh();w.camera=16;w.spawnEvents();const c=w.capsules[0];w.bullets=[new R.RomBullet(c.x-2,c.cy,0,'M')];w.collision.updateBullets(w,1/60);assert.equal(c.alive,false);assert.equal(w.pickups.length,1);});
test('暂停冻结所有计时；无效步长不改变状态；一秒重生不会卡住',()=>{const w=fresh();for(const dt of [0,-1,NaN,Infinity])w.update(dt,{right:true});assert.equal(w.time,0);w.togglePause();const before=JSON.stringify(w);for(let i=0;i<120;i++)w.update(1/60,{bomb:true,fire:true});assert.equal(JSON.stringify(w),before);});
test('人物动作排除了隐藏 OAM，保持原生像素尺寸和透明边界',()=>{for(const ids of Object.values(actors.animations))for(const id of ids){const a=actors.assets[id];assert.ok(a.width<=64&&a.height<=64,id);assert.ok(a.anchorX>=-16&&a.anchorX<=a.width+16,id);}assert.equal(actors.assets.c3_kimkoh.width,160);assert.equal(actors.assets.c3_kimkoh.height,168);});
for(let seed=1;seed<=30;seed++)test('28 屏普通按键全程 / '+seed,()=>{const w=new R.RomCityWorld(seed),p=new Pilot();w.reset();let frames=0,max=0;while(w.state==='playing'&&frames++<12000){w.update(1/60,p.next(w));w.drainEvents();max=Math.max(max,w.enemies.length+w.bullets.length);}assert.equal(w.state,'won');assert.equal(w.camera,6912);assert.equal(w.level.removedWalls.length,2);assert.ok(w.lives>0);assert.ok(max<100);});
test('随机压力 180,000 帧：状态有限、实体有界、可重开',()=>{for(let run=0;run<30;run++){const w=fresh(),random=new C.Random(run+1);for(let f=0;f<6000;f++){if(w.state!=='playing')w.reset();const input={};for(const key of ['right','left','up','down','jump','fire','bomb','swap','spin','lock'])input[key]=random.next()<.3;w.update(1/60,input);w.drainEvents();for(const n of [w.player.x,w.player.y,w.camera,w.time])assert.ok(Number.isFinite(n));assert.ok(w.bullets.length<=120);assert.ok(w.enemies.length<50);}}});
